apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-microservice-deployment
  namespace: ecommerce-namespace
  labels:
    app: orders-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-microservice
  template:
    metadata:
      labels:
        app: orders-microservice
    spec:
      containers:
      - name: orders-microservice
        image: jcdotnetecommerceregistry.azurecr.io/orders-microservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: MONGODB_HOST
          value: mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DATABASE
          value: OrdersDatabase
        - name: UsersMicroservicePort
          value: "8080"
        - name: UsersMicroserviceName
          value: apigateway
        - name: ProductsMicroservicePort
          value: "8080"
        - name: ProductsMicroserviceName
          value: apigateway
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: guest
        - name: RABBITMQ_PASS
          value: guest
        - name: RABBITMQ_PRODUCTS_EXCHANGE
          value: products.exchange
        - name: RABBITMQ_USERS_EXCHANGE
          value: users.exchange