apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-microservice-deployment
  namespace: ecommerce-namespace
  labels:
    app: products-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-microservice
  template:
    metadata:
      labels:
        app: products-microservice
    spec:
      containers:
      - name: products-microservice
        image: jcdotnetecommerceregistry.azurecr.io/products-microservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: ecommerceproductsdatabase
        - name: MYSQL_USERNAME
          value: root
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: guest
        - name: RABBITMQ_PASS
          value: guest
        - name: RABBITMQ_PRODUCTS_EXCHANGE
          value: products.exchange